name: diet_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  fl_chart: ^1.1.0
  lottie: ^3.3.1
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  equatable: ^2.0.7
  injectable: ^2.5.1
  json_serializable: ^6.11.0
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  bot_toast: ^4.1.3
  colorize: ^3.0.0
  connectivity_plus: ^6.1.5
  go_router: ^16.2.1
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.2
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  flutter_local_notifications: ^19.2.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_messaging: ^15.2.6
  path_provider: ^2.1.5
  easy_localization: ^3.0.7+1
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  skeletonizer: ^2.1.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.0
  injectable_generator: ^2.8.1
  retrofit_generator: ^10.0.2
  pretty_dio_logger: ^1.4.0
  hive_ce_generator: ^1.9.3
  go_router_builder: ^4.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lotties/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
    - family: IBMPLEX_SANS_ARABIC
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
        - asset: assets/fonts/IBMPlexSansArabic-ExtraBold.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Black.ttf