// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:diet_tracker/src/core/data/models/user_information.dart';
import 'package:diet_tracker/src/core/data/models/user_local_settings.dart';
import 'package:diet_tracker/src/core/data/models/user_settings.dart';
import 'package:diet_tracker/src/core/enums/app_theme_types.dart';
import 'package:diet_tracker/src/core/enums/user_auth.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppThemeTypeAdapter());
    registerAdapter(UserAuthAdapter());
    registerAdapter(UserInformationAdapter());
    registerAdapter(UserLocalSettingsAdapter());
    registerAdapter(UserSettingsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppThemeTypeAdapter());
    registerAdapter(UserAuthAdapter());
    registerAdapter(UserInformationAdapter());
    registerAdapter(UserLocalSettingsAdapter());
    registerAdapter(UserSettingsAdapter());
  }
}
